name = "ivxenz"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-xmin/blob/master/LICENSE.md"
description = "ivxenz: Vikram's hack of XMin"
tags = ["minimal", "blog", "personal", "clean", "simple"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Vikram Saraph"
  homepage = "https://vikramsaraph.com"
